version: "3.7"

services:
  server:
    image: golang
    env_file:
        - secrets.env
    command: >
        bash -c "
            cd /build                   &&
            ./scripts/build.sh          &&
            ./bin/bin/drone-server
        "
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./scripts:/build/scripts
    ports:
      - "8080:8080"

