version: "3.1"

services:
  server:
    image: golang
    env_file:
        - secrets.env
    command: >
        bash -c "
            /build/scripts/build.sh
        "
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./build:/build
      - ./cache:/root/.cache/
    ports:
      - "80:80"
      - "443:443"

